//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAjaxCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public int personID { get; set; }
        public string personName { get; set; }
        public string personSurname { get; set; }
        public string personMail { get; set; }
        public Nullable<int> personDep { get; set; }
        public Nullable<bool> personeDelete { get; set; }
        public Nullable<int> personNumber { get; set; }
    
        public virtual department department { get; set; }
    }
}
